spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/sportShop2'
    username: postgres
    password: rootroot
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
logging:
  file:
    name: log.txt